### ISSUE TITLE
Add header title item to list view

### ISSUE THREAD

**Issue by jpkrause** [ShelterTech/see-me#14]
This will show what the items on the list are in a textual manner to supplement the visual icon indication of what the section is.

**Comment by jpkrause** [comment]
@wrendo let me know what you want this to look like. It can be a thin list item that just has the text or it can be a larger list item, etc.

**Comment by wrendo** [comment]
assets done, just needs integration

**Comment by jpkrause** [comment]
Completed by referenced commit. Closing.
