### ISSUE TITLE
List view does not load

### ISSUE THREAD

**Issue by wrendo** [ShelterTech/see-me#26]
List view does not load on new update of app

**Comment by jpkrause** [comment]
It doesn't load for any of the sections? What is the error? What are the exact steps to see this?

**Comment by jpkrause** [comment]
This is happening because of the AB test that shows maps first causing a bug with the way the switching logic works. Will fix shortly.

**Comment by jpkrause** [comment]
This has been fixed in the referenced commit. Closing.
