### ISSUE TITLE
Main screen icon positioning

### ISSUE THREAD

**Issue by wrendo** [ShelterTech/see-me#27]
Need to bring 4 middle icons closer to middle on the home screen. Let me know if you need x/y coordinates

**Comment by jpkrause** [comment]
What I need is the locations of items relative to one another. I need to know the padding between the icons and the center text, between each other, and between the title text and the top three icons and between the bottom of the screen and the bottom three icons. Absolute positions are not useful as all of my layouts are based on relative positioning and use padding and margins.
