### ISSUE TITLE
scrolling over acceleration

### ISSUE THREAD

**Issue by wrendo** [ShelterTech/see-me#3]
If user scrolls from the bottom of the list quickly and hits a certain acceleration point, the list hits the top and bounces to the bottom. Inconsistent to reproduce, but happens often enough.

**Comment by jpkrause** [comment]
This is apparently a bug with the Android AOSP code (meaning an OS issue) and likely cannot be fixed by us. https://code.google.com/p/android/issues/detail?id=159739
Closing as wontfix
