### ISSUE TITLE
Default to map view on category view

### ISSUE THREAD

**Issue by wrendo** [ShelterTech/see-me#6]
let's test the map view as default view for when users choose a category view

**Comment by jpkrause** [comment]
For now we will have the test picked on the client side at app's first start and saved in shared prefs, send what version of the a/b test is set in the analytics event

**Comment by jpkrause** [comment]
This has been implemented by the referenced commit. Need to verify that the test is functioning.

**Comment by jpkrause** [comment]
This is verified as working. Closing.

**Comment by jpkrause** [comment]
We need to determine what metrics need to be tracked in order to discern if users like it better one way or the other. Otherwise this AB test is useless and just gives a different experience to users with no data to show us the difference it makes.

**Comment by jpkrause** [comment]
Decided to remove this AB test
